cc_binary(
  name = "main",
  srcs = ["main.cc"],
  deps = [
    "@com_google_absl//absl/status:statusor",
    "@com_google_absl//absl/status:status",
    "@com_google_absl//absl/strings:string_view",
    "@status_macros//:status_macros",
    "@com_github_google_glog//:glog",
    "@com_github_gflags_gflags//:gflags",
  ],
)
